CREATE TABLE [dbo].[Day]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Date] DATE NOT NULL, 
    [Goal] UNIQUEIDENTIFIER NOT NULL, 
    [Habbit] UNIQUEIDENTIFIER NOT NULL, 
    [Result] UNIQUEIDENTIFIER NOT NULL, 
    [Task] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT FK_Day_ToGoal FOREIGN KEY (Goal) REFERENCES Goal(Id), 
    CONSTRAINT FK_Day_ToHabbit FOREIGN KEY (Habbit) REFERENCES Habbit(Id), 
    CONSTRAINT FK_Day_ToResult FOREIGN KEY (Result) REFERENCES DayResult(Id), 
    CONSTRAINT FK_Day_ToTask FOREIGN KEY (Task) REFERENCES Task(Id) 
)
