CREATE TABLE [dbo].[Sprint]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [StartDate] DATE NOT NULL, 
    [EndTime] DATE NOT NULL, 
    [Goal] UNIQUEIDENTIFIER NOT NULL, 
    [Habbit] UNIQUEIDENTIFIER NOT NULL, 
    [Result] UNIQUEIDENTIFIER NOT NULL, 
    [Week] UNIQUEIDENTIFIER NOT NULL, 
    [Reward] TEXT NOT NULL
)
