CREATE TABLE [dbo].[Sprint]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [StartDate] DATE NOT NULL, 
    [EndTime] DATE NOT NULL, 
    [Goal] UNIQUEIDENTIFIER NOT NULL, 
    [Habbit] UNIQUEIDENTIFIER NOT NULL, 
    [Result] UNIQUEIDENTIFIER NOT NULL, 
    [Week] UNIQUEIDENTIFIER NOT NULL, 
    [Reward] TEXT NOT NULL, 
    CONSTRAINT [FK_Sprint_ToGoal] FOREIGN KEY (Goal) REFERENCES [Goal](Id), 
    CONSTRAINT [FK_Sprint_ToHabbit] FOREIGN KEY (Habbit) REFERENCES [Habbit](Id), 
    CONSTRAINT [FK_Sprint_ToResult] FOREIGN KEY (Result) REFERENCES [Result](Id), 
    CONSTRAINT [FK_Sprint_ToWeek] FOREIGN KEY (Week) REFERENCES [Week](Id)
)
