CREATE TABLE [dbo].[Week]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Day] UNIQUEIDENTIFIER NOT NULL, 
    [Goal] UNIQUEIDENTIFIER NOT NULL, 
    [Result] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Week_ToDay] FOREIGN KEY (Day) REFERENCES [Day](Id), 
    CONSTRAINT [FK_Week_ToGoal] FOREIGN KEY (Goal) REFERENCES [Goal](Id), 
    CONSTRAINT [FK_Week_ToResult] FOREIGN KEY (Result) REFERENCES [Result](Id)
)
